/* Generated By:JJTree: Do not edit this line. ASTand_clause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTand_clause extends SimpleNode {
  public ASTand_clause(int id) {
    super(id);
  }

  public ASTand_clause(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0192a48c72e60229f5c0c71854e796e8 (do not edit this line) */
