/* Generated By:JJTree: Do not edit this line. ASTbool_simple.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbool_simple extends SimpleNode {
  public ASTbool_simple(int id) {
    super(id);
  }

  public ASTbool_simple(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f28363cd11fdef96e63170cf5e81ac21 (do not edit this line) */
