/* Generated By:JJTree: Do not edit this line. ASTcomparator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcomparator extends SimpleNode {
  public ASTcomparator(int id) {
    super(id);
  }

  public ASTcomparator(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95d7a0c150f7fc75bc1beb8b032420ee (do not edit this line) */
