/* Generated By:JJTree: Do not edit this line. ASTelifs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTelifs extends SimpleNode {
  public ASTelifs(int id) {
    super(id);
  }

  public ASTelifs(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1529ca7e8f1201c47a3482020678eadd (do not edit this line) */
