/* Generated By:JJTree: Do not edit this line. ASTfor_stat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfor_stat extends SimpleNode {
  public ASTfor_stat(int id) {
    super(id);
  }

  public ASTfor_stat(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f6ebc9d8c93bd824f3a49d35731c4eb1 (do not edit this line) */
