/* Generated By:JJTree: Do not edit this line. ASTif_stat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTif_stat extends SimpleNode {
  public ASTif_stat(int id) {
    super(id);
  }

  public ASTif_stat(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=79c8a3fc47c734693eeafbb88adb4732 (do not edit this line) */
