/* Generated By:JJTree: Do not edit this line. ASTnot_clause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnot_clause extends SimpleNode {
  public ASTnot_clause(int id) {
    super(id);
  }

  public ASTnot_clause(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=02178d5bb8a0ac3ced3bfe64dea9d39b (do not edit this line) */
