/* Generated By:JJTree: Do not edit this line. ASTproduct.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTproduct extends SimpleNode {
  public ASTproduct(int id) {
    super(id);
  }

  public ASTproduct(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=baff2482e99ad750fda14d3f4cf9990a (do not edit this line) */
