/* Generated By:JJTree: Do not edit this line. ASTprintln_stat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprintln_stat extends SimpleNode {
  public ASTprintln_stat(int id) {
    super(id);
  }

  public ASTprintln_stat(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1fa2fed60720450c7d08ba7b876ea0c4 (do not edit this line) */
