/* Generated By:JJTree: Do not edit this line. ASTreturnval.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturnval extends SimpleNode {
  public ASTreturnval(int id) {
    super(id);
  }

  public ASTreturnval(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=01be57c5ce4f29b7b5fd3268d610bba0 (do not edit this line) */
