/* Generated By:JJTree: Do not edit this line. ASTstatement_LL1.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement_LL1 extends SimpleNode {
  public ASTstatement_LL1(int id) {
    super(id);
  }

  public ASTstatement_LL1(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ef84632ce1a9ed29e88fe2a95b393ee (do not edit this line) */
