/* Generated By:JJTree: Do not edit this line. ASTsimple_term.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsimple_term extends SimpleNode {
  public ASTsimple_term(int id) {
    super(id);
  }

  public ASTsimple_term(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=68174114b3c9cb33e62f73a74ea47dda (do not edit this line) */
