/* Generated By:JJTree: Do not edit this line. ASTwhile_stat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhile_stat extends SimpleNode {
  public ASTwhile_stat(int id) {
    super(id);
  }

  public ASTwhile_stat(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=505a5a2c9bc97cc46e496d467ab03b30 (do not edit this line) */
