/* Generated By:JavaCC: Do not edit this line. VNMDefaultVisitor.java Version 7.0.9 */
public class VNMDefaultVisitor implements VNMVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTS node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstatement_LL1 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTbody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTclause node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTident_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_call node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTboolean_call node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexp_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcondition_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTreturn_stat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTreturnval node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprint_stat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprintln_stat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprint_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTassign_stat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTif_stat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTelifs node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfor_stat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTwhile_stat node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcondition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTand_clause node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnot_clause node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcomparison node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcomparator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTproduct node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTterm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsimple_term node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvec_const node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTbool_simple node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=ab765ede3f9b7c2d0d7c530a097b0ade (do not edit this line) */
