/* Generated By:JavaCC: Do not edit this line. VNMTreeConstants.java Version 7.0.9 */
public interface VNMTreeConstants
{
  public int JJTVOID = 0;
  public int JJTS = 1;
  public int JJTSTATEMENT_LL1 = 2;
  public int JJTSTATEMENT = 3;
  public int JJTBODY = 4;
  public int JJTCLAUSE = 5;
  public int JJTVAR_DECL = 6;
  public int JJTFN_DECL = 7;
  public int JJTIDENT_LIST = 8;
  public int JJTFN_CALL = 9;
  public int JJTBOOLEAN_CALL = 10;
  public int JJTEXP_LIST = 11;
  public int JJTCONDITION_LIST = 12;
  public int JJTRETURN_STAT = 13;
  public int JJTRETURNVAL = 14;
  public int JJTPRINT_STAT = 15;
  public int JJTPRINTLN_STAT = 16;
  public int JJTPRINT_LIST = 17;
  public int JJTASSIGN_STAT = 18;
  public int JJTIF_STAT = 19;
  public int JJTELIFS = 20;
  public int JJTFOR_STAT = 21;
  public int JJTWHILE_STAT = 22;
  public int JJTCONDITION = 23;
  public int JJTAND_CLAUSE = 24;
  public int JJTNOT_CLAUSE = 25;
  public int JJTCOMPARISON = 26;
  public int JJTCOMPARATOR = 27;
  public int JJTEXPRESSION = 28;
  public int JJTPRODUCT = 29;
  public int JJTTERM = 30;
  public int JJTSIMPLE_TERM = 31;
  public int JJTVEC_CONST = 32;
  public int JJTIDENTIFIER = 33;
  public int JJTBOOL_SIMPLE = 34;


  public String[] jjtNodeName = {
    "void",
    "S",
    "statement_LL1",
    "statement",
    "body",
    "clause",
    "var_decl",
    "fn_decl",
    "ident_list",
    "fn_call",
    "boolean_call",
    "exp_list",
    "condition_list",
    "return_stat",
    "returnval",
    "print_stat",
    "println_stat",
    "print_list",
    "assign_stat",
    "if_stat",
    "elifs",
    "for_stat",
    "while_stat",
    "condition",
    "and_clause",
    "not_clause",
    "comparison",
    "comparator",
    "expression",
    "product",
    "term",
    "simple_term",
    "vec_const",
    "identifier",
    "bool_simple",
  };
}
/* JavaCC - OriginalChecksum=083565af94f49671138cb006d6594565 (do not edit this line) */
